import { defineConfig } from "vite";
import laravel from "laravel-vite-plugin";
import tailwindcss from "@tailwindcss/vite";
import obfuscatorPlugin from "vite-plugin-javascript-obfuscator";
import fs from 'fs';

const isLocal = process.env.APP_ENV === 'local';

export default defineConfig({
    plugins: [
        laravel({
            input: [
                "resources/css/app.css",
                "resources/css/cadastroempresa.css",
                "resources/css/cadastroFornecedores.css",
                "resources/css/cadastroProdutos.css",
                "resources/css/cadastrousuario.css",
                "resources/css/configadm.css",
                "resources/css/configmenu.css",
                "resources/css/confirmarcadastro.css",
                "resources/css/edicaoOrdemDeProducao.css",
                "resources/css/editarcontaOwner.css",
                "resources/css/editarempresa.css",
                "resources/css/editarfuncionarios.css",
                "resources/css/editartelainicial.css",
                "resources/css/email.css",
                "resources/css/gerenciarfuncionarios.css",
                "resources/css/gerenciarOrdensDeProducao.css",
                "resources/css/home.css",
                "resources/css/homeadm.css",
                "resources/css/login.css",
                "resources/css/loginadm.css",
                "resources/css/menu.css",
                "resources/css/menuadm.css",
                "resources/css/modalOrdemDeProducao.css",
                "resources/css/redefinirsenha.css",
                "resources/css/relatoriosadm.css",
                "resources/css/requisicao.css",
                "resources/css/selecionar-empresa.css",
                "resources/css/telacarregamento.css",
                "resources/css/todasContas.css",
                "resources/css/todosFornecedores.css",
                "resources/css/todosProdutos.css",
                "resources/css/visualizarContas.css",
                "resources/css/visualizarFornecedores.css",
                "resources/css/visualizarProdutos.css",
                "resources/js/app.js",
                "resources/js/API_JS/api.js",
                "resources/js/assets/auth.js",
                "resources/js/assets/mascaras.js",
                "resources/js/assets/validacoes.js",
                "resources/js/scriptJS/banco.js",
                "resources/js/scriptJS/dom.js",
                "resources/js/scriptJS/estado.js",
                "resources/js/scriptJS/eventos.js",
                "resources/js/scriptJS/modal.js",
                "resources/js/scriptJS/persistencia.js",
                "resources/js/scriptJS/renderizacao.js",
                "resources/js/scriptJS/validacoes.js",
                "resources/js/toast/toast.js",
                "resources/js/bootstrap.js",
                "resources/js/cadastroempresa.js",
                "resources/js/cadastroFornecedores.js",
                "resources/js/cadastroProdutos.js",
                "resources/js/cadastrousuario.js",
                "resources/js/configadm.js",
                "resources/js/configmenu.js",
                "resources/js/confirmarcadastro.js",
                "resources/js/edicaoOrdemDeProducao.js",
                "resources/js/editarcontaOwner.js",
                "resources/js/editarempresa.js",
                "resources/js/editarfuncionarios.js",
                "resources/js/editartelainicial.js",
                "resources/js/gerenciarfuncionarios.js",
                "resources/js/gerenciarOrdensDeProducao.js",
                "resources/js/home.js",
                "resources/js/homeadm.js",
                "resources/js/login.js",
                "resources/js/loginadm.js",
                "resources/js/menu.js",
                "resources/js/menuadm.js",
                "resources/js/modalOrdemDeProducao.js",
                "resources/js/progressoEtapas.js",
                "resources/js/relatoriosadm.js",
                "resources/js/requisicao.js",
                "resources/js/selecionar-empresa.js",
                "resources/js/telacarregamento.js",
                "resources/js/todasContas.js",
                "resources/js/todosFornecedores.js",
                "resources/js/todosProdutos.js",
                "resources/js/visualizarContas.js",
                "resources/js/visualizarFornecedor.js",
                "resources/js/visualizarProdutos.js",
            ],
            refresh: true,
        }),
        tailwindcss(),
        obfuscatorPlugin({
            exclude: [/api\.js/],
            apply: 'build',
            debugProtection: false,
            options: {
                compact: true,
                controlFlowFlattening: true,
                controlFlowFlatteningThreshold: 0.75,
                deadCodeInjection: true,
                deadCodeInjectionThreshold: 0.4,
                debugProtection: false,
                disableConsoleOutput: false,
                identifierNamesGenerator: "hexadecimal",
                rotateStringArray: true,
                selfDefending: false,
                stringArray: true,
                stringArrayEncoding: ["rc4"],
                stringArrayThreshold: 0.75,
                transformObjectKeys: false,
                unicodeEscapeSequence: false,
            },
        }),
    ],
    build: {
        sourcemap: false,
        rollupOptions: {
            output: {
                entryFileNames: "assets/[hash].js",
                chunkFileNames: "assets/[hash].js",
                assetFileNames: "assets/[hash][extname]",
                compact: true,
            },
        },
    },
    esbuild: {
        legalComments: "none",
        minifyIdentifiers: true,
        minifySyntax: true,
        minifyWhitespace: true,
    },

    // Configurações apenas para desenvolvimento local
    ...(isLocal && {
        server: {
            host: "sewfy.local",
            port: 5173,
            https: {
                key: fs.readFileSync("C:/certs/sewfy.local+1-key.pem"),
                cert: fs.readFileSync("C:/certs/sewfy.local+1.pem"),
            },
            origin: "https://sewfy.local:5173",
            watch: {
                ignored: ["**/storage/framework/views/**"],
            },
            cors: {
                origin: "https://sewfy.local",
                credentials: true,
            },
            proxy: {
                '/api': {
                    target: 'https://api.sewfy.local',
                    changeOrigin: true,
                    secure: false,
                },
                '/sanctum': {
                    target: 'https://api.sewfy.local',
                    changeOrigin: true,
                    secure: false,
                },
            },
        },
    }),
});